export const books = [
  {
    number: 1,
    title: "Harry Potter and the Sorcerer's Stone",
    originalTitle: "Harry Potter and the Sorcerer's Stone",
    releaseDate: "Jun 26, 1997",
    description:
      "On his birthday, Harry Potter discovers that he is the son of two well-known wizards, from whom he has inherited magical powers. He must attend a famous school of magic and sorcery, where he establishes a friendship with two young men who will become his companions on his adventure. During his first year at Hogwarts, he discovers that a malevolent and powerful wizard named Voldemort is in search of a philosopher's stone that prolongs the life of its owner.",
    pages: 223,
    cover:
      "https://raw.githubusercontent.com/fedeperin/potterapi/main/public/images/covers/1.png",
    index: 0,
  },
  {
    number: 2,
    title: "Harry Potter and the chamber of secrets",
    originalTitle: "Harry Potter and the chamber of secrets",
    releaseDate: "Jul 2, 1998",
    description:
      "Harry Potter and the sophomores investigate a malevolent threat to their Hogwarts classmates, a menacing beast that hides within the castle.",
    pages: 251,
    cover:
      "https://raw.githubusercontent.com/fedeperin/potterapi/main/public/images/covers/2.png",
    index: 1,
  },
  {
    number: 3,
    title: "Harry Potter and the Prisoner of Azkaban",
    originalTitle: "Harry Potter and the Prisoner of Azkaban",
    releaseDate: "Jul 8, 1999",
    description:
      "Harry's third year of studies at Hogwarts is threatened by Sirius Black's escape from Azkaban prison. Apparently, it is a dangerous wizard who was an accomplice of Lord Voldemort and who will try to take revenge on Harry Potter.",
    pages: 317,
    cover:
      "https://raw.githubusercontent.com/fedeperin/potterapi/main/public/images/covers/3.png",
    index: 2,
  },
  {
    number: 4,
    title: "Harry Potter and the Goblet of Fire",
    originalTitle: "Harry Potter and the Goblet of Fire",
    releaseDate: "Jul 8, 2000",
    description:
      "Hogwarts prepares for the Triwizard Tournament, in which three schools of wizardry will compete. To everyone's surprise, Harry Potter is chosen to participate in the competition, in which he must fight dragons, enter the water and face his greatest fears.",
    pages: 636,
    cover:
      "https://raw.githubusercontent.com/fedeperin/potterapi/main/public/images/covers/4.png",
    index: 3,
  },
  {
    number: 5,
    title: "Harry Potter and the Order of the Phoenix",
    originalTitle: "Harry Potter and the Order of the Phoenix",
    releaseDate: "Jun 21, 2003",
    description:
      "In his fifth year at Hogwarts, Harry discovers that many members of the wizarding community do not know the truth about his encounter with Lord Voldemort. Cornelius Fudge, Minister of Magic, appoints Dolores Umbridge as Defense Against the Dark Arts teacher because he believes that Professor Dumbledore plans to take over his job. But his teachings are inadequate, so Harry prepares the students to defend the school against evil.",
    pages: 766,
    cover:
      "https://raw.githubusercontent.com/fedeperin/potterapi/main/public/images/covers/5.png",
    index: 4,
  },
  {
    number: 6,
    title: "Harry Potter and the Half-Blood Prince",
    originalTitle: "Harry Potter and the Half-Blood Prince",
    releaseDate: "Jul 16, 2005",
    description:
      "Harry discovers a powerful book and, while trying to discover its origins, collaborates with Dumbledore in the search for a series of magical objects that will aid in the destruction of Lord Voldemort.",
    pages: 607,
    cover:
      "https://raw.githubusercontent.com/fedeperin/potterapi/main/public/images/covers/6.png",
    index: 5,
  },
  {
    number: 7,
    title: "Harry Potter and the Deathly Hallows",
    originalTitle: "Harry Potter and the Deathly Hallows",
    releaseDate: "Jul 21, 2007",
    description:
      "Harry, Ron and Hermione go on a dangerous mission to locate and destroy the secret of Voldemort's immortality and destruction - the Horcruces. Alone, without the guidance of their teachers or the protection of Professor Dumbledore, the three friends must lean on each other more than ever. But there are Dark Forces in between that threaten to tear them apart. Harry Potter is getting closer and closer to the task for which he has been preparing since the first day he set foot in Hogwarts: the last battle with Voldemort.",
    pages: 607,
    cover:
      "https://raw.githubusercontent.com/fedeperin/potterapi/main/public/images/covers/7.png",
    index: 6,
  },
  {
    number: 8,
    title: "Harry Potter and the Cursed Child",
    originalTitle: "Harry Potter and the Cursed Child",
    releaseDate: "Jul 30, 2016",
    description:
      "Harry's second son entered Hogwarts, but in Slytherin. His relationship with Harry is getting worse and he became close friends with Draco's son, Scorpius Malfoy who is said to be Lord Voldemort's son.",
    pages: 336,
    cover:
      "https://raw.githubusercontent.com/fedeperin/potterapi/main/public/images/covers/8.png",
    index: 7,
  },
];

export const houses = [
  {
    house: "Gryffindor",
    emoji: "🦁",
    image: "/harry-potter-world/gryffindor.jpg",
    founder: "Godric Gryffindor",
    colors: ["#5D0205", "#B57E09"],
    animal: "Lion",
    index: 0,
  },
  {
    house: "Hufflepuff",
    emoji: "🦡",
    image: "/harry-potter-world/hufflepuff.jpg",
    founder: "Helga Hufflepuff",
    colors: ["#DDB103", "#080808"],
    animal: "Badger",
    index: 1,
  },
  {
    house: "Ravenclaw",
    emoji: "🦅",
    image: "/harry-potter-world/ravenclaw.jpg",
    founder: "Rowena Ravenclaw",
    colors: ["#037EA0", "#E0C65D"],
    animal: "Raven",
    index: 2,
  },
  {
    house: "Slytherin",
    emoji: "🐍",
    image: "/harry-potter-world/slytherin.jpg",
    founder: "Salazar Slytherin",
    colors: ["#042D03", "#A1A1A1"],
    animal: "Snake",
    index: 3,
  },
];

export const spells = [
  {
    id: "c76a2922-ba4c-4278-baab-44defb631236",
    name: "Aberto",
    description: "Opens locked doors",
  },
  {
    id: "06485500-d023-4799-93fd-77f2c3341aa3",
    name: "Accio",
    description: "Summons objects",
  },
  {
    id: "acbc0ae1-12e1-4813-b51e-09d22de40475",
    name: "Aguamenti",
    description: "Summons water",
  },
  {
    id: "c9d2f389-a419-4f7e-8d3d-254959638019",
    name: "Alohomora",
    description: "Unlocks objects",
  },
  {
    id: "018429a5-15d5-41af-bf8f-98a966733d77",
    name: "Anapneo",
    description: "Clears someone's airway",
  },
  {
    id: "c828685c-52d2-466d-bcc6-fbcd8376cfb5",
    name: "Aparecium",
    description: "Reveals secret written messages",
  },
  {
    id: "7fdd393c-2608-4ef3-9fd0-f691ad6f8b88",
    name: "Apparate",
    description:
      "A non-verbal transportation spell that allows a witch or wizard to instantly travel on the spot and appear at another location (disapparate is the opposite)",
  },
  {
    id: "73886d47-2808-4861-ae40-956f4cb56272",
    name: "Ascendio",
    description: "Propells someone into the air",
  },
  {
    id: "9a6b6854-8858-4b21-b761-12526a154597",
    name: "Avada Kedavra",
    description:
      "Also known as The Killing Curse, the most evil spell in the Wizarding World; one of three Unforgivable Curses; Harry Potter is the only known witch or wizard to survive it",
  },
  {
    id: "b6f20bba-c0db-4ad2-8ac6-2a375a596287",
    name: "Avis",
    description: "Conjures a small flock of birds",
  },
  {
    id: "48edfe4d-ddfc-49ac-8065-bd7e73c73778",
    name: "Bat",
    description: "Bogey Hex - Turns the target's boogers into bats",
  },
  {
    id: "6bd8d5c1-9375-4b70-8d6e-ad019176c7a2",
    name: "Bombardo",
    description: "Creates an explosion",
  },
  {
    id: "8fc19d10-3130-4b85-95c1-f2a51ba5ee3c",
    name: "Brackium Emendo",
    description: "Heals broken bones",
  },
  {
    id: "f08c17fa-7bf9-49bf-9fba-a7806815bc80",
    name: "Capacious Extremis",
    description:
      "Known as the Extension Charm, it's a complicated spell that can greatly expand or extend the capacity of an object or space without affecting it externally",
  },
  {
    id: "55dec867-ac07-4975-94c7-090f6fd25c86",
    name: "Confundo",
    description:
      "Known as the Confundus Charm, it causes confusion of the target",
  },
];

export const characters = [
  {
    id: "4c7e6819-a91a-45b2-a454-f931e4a7cce3",
    name: "Hermione Granger",
    alternate_names: ["Hermy", "Know-it-all", "Miss Grant", "Herm-own-ninny"],
    species: "human",
    gender: "female",
    house: "Gryffindor",
    dateOfBirth: "19-09-1979",
    yearOfBirth: 1979,
    wizard: true,
    ancestry: "muggleborn",
    eyeColour: "brown",
    hairColour: "brown",
    wand: {
      wood: "vine",
      core: "dragon heartstring",
      length: 10.75,
    },
    patronus: "otter",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Emma Watson",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/hermione.jpeg",
  },
  {
    id: "c3b1f9a5-b87b-48bf-b00d-95b093ea6390",
    name: "Ron Weasley",
    alternate_names: [
      "Dragomir Despard",
      "Ronald",
      "Ickle Ronniekins",
      "Ronnie",
      "Wheezy",
      "Won-Won",
      "Roonil Wazlib",
    ],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "01-03-1980",
    yearOfBirth: 1980,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "blue",
    hairColour: "red",
    wand: {
      wood: "willow",
      core: "unicorn tail hair",
      length: 14,
    },
    patronus: "Jack Russell terrier",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Rupert Grint",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/ron.jpg",
  },
  {
    id: "af95bd8a-dfae-45bb-bc69-533860d34129",
    name: "Draco Malfoy",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: "05-06-1980",
    yearOfBirth: 1980,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "grey",
    hairColour: "blonde",
    wand: {
      wood: "hawthorn",
      core: "unicorn tail hair",
      length: 10,
    },
    patronus: "",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Tom Felton",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/draco.jpg",
  },
  {
    id: "ca3827f0-375a-4891-aaa5-f5e8a5bad225",
    name: "Minerva McGonagall",
    alternate_names: [],
    species: "human",
    gender: "female",
    house: "Gryffindor",
    dateOfBirth: "04-10-1925",
    yearOfBirth: 1925,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "",
    hairColour: "black",
    wand: {
      wood: "fir",
      core: "dragon heartstring",
      length: 9.5,
    },
    patronus: "tabby cat",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Dame Maggie Smith",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/mcgonagall.jpg",
  },
  {
    id: "d5c4daa3-c726-426a-aa98-fb40f3fba816",
    name: "Cedric Diggory",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "Hufflepuff",
    dateOfBirth: null,
    yearOfBirth: 1977,
    wizard: true,
    ancestry: "",
    eyeColour: "grey",
    hairColour: "brown",
    wand: {
      wood: "ash",
      core: "unicorn hair",
      length: 12.25,
    },
    patronus: "",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Robert Pattinson",
    alternate_actors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/cedric.png",
  },
  {
    id: "8f9aa40b-5d7c-441e-ad32-4564ecda3b70",
    name: "Cho Chang",
    alternate_names: [],
    species: "human",
    gender: "female",
    house: "Ravenclaw",
    dateOfBirth: "07-04-1979",
    yearOfBirth: 1979,
    wizard: true,
    ancestry: "",
    eyeColour: "brown",
    hairColour: "black",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "swan",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Katie Leung",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/cho.jpg",
  },
  {
    id: "3569d265-bd27-44d8-88e8-82fb0a848374",
    name: "Severus Snape",
    alternate_names: ["Half-Blood Prince", "Snivellus", "Sev"],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: "09-01-1960",
    yearOfBirth: 1960,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "black",
    hairColour: "black",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "doe",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Alan Rickman",
    alternate_actors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/snape.jpg",
  },
  {
    id: "36bfefd0-e0bb-4d11-be98-d1ef6117a77a",
    name: "Rubeus Hagrid",
    alternate_names: ["Professor Hagrid", "Hagger"],
    species: "half-giant",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "06-12-1928",
    yearOfBirth: 1928,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "black",
    hairColour: "black",
    wand: {
      wood: "oak",
      core: "",
      length: 16,
    },
    patronus: "",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Robbie Coltrane",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/hagrid.png",
  },
  {
    id: "3db6dc51-b461-4fa4-a6e4-b1ff352221c5",
    name: "Neville Longbottom",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "30-07-1980",
    yearOfBirth: 1980,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "",
    hairColour: "blonde",
    wand: {
      wood: "cherry",
      core: "unicorn tail hair",
      length: 13,
    },
    patronus: "Non-Corporeal",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Matthew Lewis",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/neville.jpg",
  },
  {
    id: "861c4cde-2f0f-4796-8d8f-9492e74b2573",
    name: "Luna Lovegood",
    alternate_names: ["Loony Lovegood"],
    species: "human",
    gender: "female",
    house: "Ravenclaw",
    dateOfBirth: "13-02-1981",
    yearOfBirth: 1981,
    wizard: true,
    ancestry: "",
    eyeColour: "silver",
    hairColour: "blonde",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "hare",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Evanna Lynch",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/luna.jpg",
  },
  {
    id: "1cd6dc64-01a9-4379-9cfd-1a7167ba1bb1",
    name: "Ginny Weasley",
    alternate_names: [],
    species: "human",
    gender: "female",
    house: "Gryffindor",
    dateOfBirth: "11-08-1981",
    yearOfBirth: 1981,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "brown",
    hairColour: "red",
    wand: {
      wood: "yew",
      core: "",
      length: null,
    },
    patronus: "horse",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Bonnie Wright",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/ginny.jpg",
  },
  {
    id: "2cfd2d4b-5d1e-4dc5-8837-37a97c7e2f2f",
    name: "Sirius Black",
    alternate_names: ["Padfoot", "Snuffles"],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "03-11-1959",
    yearOfBirth: 1959,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "grey",
    hairColour: "black",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "hare",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Gary Oldman",
    alternate_actors: ["James Walters", "Rohan Gotobed"],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/sirius.JPG",
  },
  {
    id: "b8f9095b-9de6-4d7d-83e0-4391af8f22e4",
    name: "Remus Lupin",
    alternate_names: ["Professor Lupin", "Moony", "Remus John Lupin"],
    species: "werewolf",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "10-03-1960",
    yearOfBirth: 1960,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "green",
    hairColour: "brown",
    wand: {
      wood: "cypress",
      core: "unicorn tail hair",
      length: 10.25,
    },
    patronus: "wolf",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "David Thewlis",
    alternate_actors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/lupin.jpg",
  },
  {
    id: "dd925874-e800-4eb4-9f0d-4d0fed15634b",
    name: "Arthur Weasley",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    dateOfBirth: "06-02-1950",
    yearOfBirth: 1950,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "blue",
    hairColour: "red",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "weasel",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Mark Williams",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/arthur.jpg",
  },
  {
    id: "6afb1960-febd-418d-b604-e50c1b59459b",
    name: "Bellatrix Lestrange",
    alternate_names: ["Bella"],
    species: "human",
    gender: "female",
    house: "Slytherin",
    dateOfBirth: null,
    yearOfBirth: 1951,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "brown",
    hairColour: "black",
    wand: {
      wood: "walnut",
      core: "dragon heartstring",
      length: 12.75,
    },
    patronus: "",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Helena Bonham Carter",
    alternate_actors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/bellatrix.jpg",
  },
  {
    id: "efa802c8-ae18-4ae1-a524-49df21d05939",
    name: "Lord Voldemort",
    alternate_names: [
      "Tom Riddle",
      "Tom Marvolo Riddle",
      "You-Know-Who",
      "He Who Must Not Be Named",
      "the Dark Lord",
      "the Heir of Slytherin",
    ],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: "31-12-1926",
    yearOfBirth: 1926,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "Scarlet",
    hairColour: "bald",
    wand: {
      wood: "yew",
      core: "phoenix tail feather",
      length: 13.5,
    },
    patronus: "",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Ralph Fiennes",
    alternate_actors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/voldemort.jpg",
  },
  {
    id: "2fb675cd-5505-4c8e-a54e-579e73bf4174",
    name: "Horace Slughorn",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: null,
    yearOfBirth: null,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "green",
    hairColour: "blonde",
    wand: {
      wood: "cedar",
      core: "dragon heartstring",
      length: 10.25,
    },
    patronus: "",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Jim Broadbent",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/slughorn.JPG",
  },
  {
    id: "106cf68d-a86a-415e-ad75-6ad9a4ae24e4",
    name: "Kingsley Shacklebolt",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "",
    dateOfBirth: null,
    yearOfBirth: null,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "brown",
    hairColour: "brown",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "lynx",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "George Harris",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/kingsley.jpg",
  },
  {
    id: "d58e7249-19d1-40bd-a43f-1da0497fe8aa",
    name: "Dolores Umbridge",
    alternate_names: [],
    species: "human",
    gender: "female",
    house: "Slytherin",
    dateOfBirth: null,
    yearOfBirth: null,
    wizard: true,
    ancestry: "half-blood",
    eyeColour: "brown",
    hairColour: "grey",
    wand: {
      wood: "birch",
      core: "dragon heartstring",
      length: 8,
    },
    patronus: "persian cat",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Imelda Staunton",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/umbridge.jpg",
  },
  {
    id: "43403619-70cb-4a0c-b70a-6d5cae20e602",
    name: "Lucius Malfoy",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: null,
    yearOfBirth: 1954,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "grey",
    hairColour: "blonde",
    wand: {
      wood: "elm",
      core: "dragon heartstring",
      length: 18,
    },
    patronus: "",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Jason Isaacs",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/lucius.jpg",
  },
  {
    id: "04f9eb45-d843-4e29-a7d3-0bd49ed87f85",
    name: "Vincent Crabbe",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: null,
    yearOfBirth: null,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "black",
    hairColour: "black",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Jamie Waylett",
    alternate_actors: [],
    alive: false,
    image: "https://ik.imagekit.io/hpapi/crabbe.jpg",
  },
  {
    id: "32923dab-16e1-4da1-8af7-bf9bec9ece1b",
    name: "Mr Crabbe",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "",
    dateOfBirth: null,
    yearOfBirth: null,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "",
    hairColour: "",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "",
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: "Paschal Friel",
    alternate_actors: [],
    alive: false,
    image: "",
  },
  {
    id: "a31ddc78-af12-4978-929c-3cc8a00a833e",
    name: "Gregory Goyle",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "Slytherin",
    dateOfBirth: null,
    yearOfBirth: null,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "",
    hairColour: "brown",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Josh Herdman",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/goyle.jpg",
  },
  {
    id: "0d72d9ce-9560-4e72-bd2e-f0af02f32caa",
    name: "Mr Goyle",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "",
    dateOfBirth: null,
    yearOfBirth: null,
    wizard: true,
    ancestry: "pure-blood",
    eyeColour: "",
    hairColour: "",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "",
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: "Alex Palmer",
    alternate_actors: [],
    alive: true,
    image: "",
  },
  {
    id: "b0620914-858d-46fc-8e6d-033c565e138b",
    name: "Mrs Norris",
    alternate_names: [],
    species: "cat",
    gender: "female",
    house: "",
    dateOfBirth: null,
    yearOfBirth: null,
    wizard: false,
    ancestry: "",
    eyeColour: "yellow",
    hairColour: "brown",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "Maxime, Alanis and Tommy the cats",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/norris.JPG",
  },
  {
    id: "2b82cfb8-0440-4a57-a030-6d75a40c0d98",
    name: "Argus Filch",
    alternate_names: [],
    species: "human",
    gender: "male",
    house: "",
    dateOfBirth: null,
    yearOfBirth: null,
    wizard: false,
    ancestry: "squib",
    eyeColour: "",
    hairColour: "grey",
    wand: {
      wood: "",
      core: "",
      length: null,
    },
    patronus: "",
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: "David Bradley",
    alternate_actors: [],
    alive: true,
    image: "https://ik.imagekit.io/hpapi/filch.jpg",
  },
];
